---
# tasks file for adipriyantobpn.repo-rabbitmq
- block:

  - name: include yum repository variable file
    include_vars: "repo-{{ repo_location }}.yml"

  - name: import RabbitMQ GPG key
    rpm_key:
      key: "{{ rabbitmq_gpgkey_url.replace('file://', '') }}"
      state: present
    ignore_errors: "{{ ansible_check_mode }}"

  - name: configure RabbitMQ yum repository
    yum_repository:
      name: "{{ item.key.lower() }}"
      description: "RabbitMQ for CentOS $releasever - $basearch"
      mirrorlist: "{{ item.value.mirrorlist | default(omit) }}"
      skip_if_unavailable: true
      baseurl: "{{ item.value.baseurl | default(omit) }}"
      gpgkey: "{{ rabbitmq_gpgkey_url }}"
      gpgcheck: yes
      enabled: "{{ item.value.enabled }}"
      file: "{{ item.value.file }}"
      state: present
    with_dict: "{{ rabbitmq_repo }}"
  become: True